# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acdaf15ea7b0c5e8774dbb0fd241feb5c408564a0d92135ac543a84ef50fb8192f1995291a6a87ee957e98e2916ca3d8485ccd42e970fff422f40665db5c432a

test:
  secret_key_base: 5a5b91d619a653dcee94fd5f4002fd8f07a575495801525b9a8e8867763eee4a14f4cce9d3940c6fcffe80264a909084d71feb5006063494bf775cbb7529889f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
